# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

func_dc <- function(z) {
    .Call('factorcpt_func_dc', PACKAGE = 'factorcpt', z)
}

func_dc_by <- function(z, dmby, dtby) {
    .Call('factorcpt_func_dc_by', PACKAGE = 'factorcpt', z, dmby, dtby)
}

func_coef <- function(z, scale) {
    .Call('factorcpt_func_coef', PACKAGE = 'factorcpt', z, scale)
}

func_input <- function(coef, sgn) {
    .Call('factorcpt_func_input', PACKAGE = 'factorcpt', coef, sgn)
}

func_input_on <- function(coef) {
    .Call('factorcpt_func_input_on', PACKAGE = 'factorcpt', coef)
}

